# Generated by Django 5.1.4 on 2025-01-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_utilisateur_groups_utilisateur_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('medecin', 'Medecin'), ('infirmier', 'Infirmier'), ('patient', 'Patient'), ('radiologue', 'Radiologue'), ('laboratoire', 'Laboratoire')], max_length=20),
        ),
    ]
