# Generated by Django 5.1.4 on 2025-01-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_utilisateur_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='NSS',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
