

POST http://127.0.0.1:8000/newapi/consultations/add/   HTTP/1.1
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM1OTg3MTAyLCJpYXQiOjE3MzU5ODYyMDIsImp0aSI6Ijc5OTgxZGZmNWM0YTRkZmU5OTJlMzdlY2IyNWM1OWMzIiwidXNlcl9pZCI6Mn0.b9Q65FR-yktRQVucWXyVP8PSaJ8qfIjPgdgwV4xhZZ4

{
  "dpi": 1,
  "resume": {
    "symptomes": "Severe abdominal pain and nausea",
    "diagnostic": "Gastritis",
    "details": "Advised to avoid spicy food and take antacids."
  },
  "ordonnance": {
    "prescription": [
      {
        "dose": "20mg",
        "duree": "14 days",
        "medicament": {
          "nom": "Omeprazole",
          "description": "Proton pump inhibitor",
          "quantite": 28
        }
      },
      {
        "dose": "10mg",
        "duree": "10 days",
        "medicament": {
          "nom": "Metoclopramide",
          "description": "Antiemetic and gut motility stimulator",
          "quantite": 20
        }
      }
    ]
  },
  "bilan_biologique": {
    "description": "Normal blood count"
  },
  "bilan_radiologue": {
    "description": "No abnormalities detected"
  }
}
