# Generated by Django 5.1.4 on 2024-12-21 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BilanRadiologique',
            fields=[
                ('id_bilan_radiologique', models.AutoField(primary_key=True, serialize=False)),
                ('date_bilan', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultatBiologique',
            fields=[
                ('id_resultat', models.AutoField(primary_key=True, serialize=False)),
                ('parametre', models.CharField(max_length=50)),
                ('valeur', models.FloatField()),
                ('unite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BilanBiologique',
            fields=[
                ('id_bilan_biologique', models.AutoField(primary_key=True, serialize=False)),
                ('date_bilan', models.DateTimeField()),
                ('laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.laboratoire')),
                ('resultats', models.ManyToManyField(to='examination.resultatbiologique')),
            ],
        ),
        migrations.CreateModel(
            name='Examen_Complementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('bilan_Biologique_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examination.bilanbiologique')),
                ('bilan_Radiologique_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='examination.bilanradiologique')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Examen_Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outils', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenRadiologique',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('date_examen', models.DateField()),
                ('type_radio', models.CharField(max_length=20)),
                ('radiologue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.radiologue')),
            ],
        ),
        migrations.AddField(
            model_name='bilanradiologique',
            name='examens',
            field=models.ManyToManyField(to='examination.examenradiologique'),
        ),
        migrations.CreateModel(
            name='ImageMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.AddField(
            model_name='examenradiologique',
            name='resultat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.imagemedicale'),
        ),
        migrations.CreateModel(
            name='Examen_Radiologique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_examen', models.DateField()),
                ('type_radio', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('radiologue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.radiologue')),
                ('resultat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.imagemedicale')),
            ],
        ),
    ]
