# Generated by Django 5.1.4 on 2024-12-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen_radiologique',
            old_name='radiologue_id',
            new_name='radiologue',
        ),
        migrations.RenameField(
            model_name='examen_radiologique',
            old_name='resultat_id',
            new_name='resultat',
        ),
    ]
