# Generated by Django 5.1.4 on 2025-01-02 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0002_diagnostic_consultations_diagnostic_date_creation_and_more'),
        ('users', '0006_alter_patient_nss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient', unique=True),
        ),
    ]
