# Generated by Django 5.1.4 on 2025-01-02 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0003_alter_dpi_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='certificatMedical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.certificatmedical'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='compte_Rendu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.compte_rendu'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.diagnostic'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='hospitalisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.hospital'),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='soin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.soin'),
        ),
    ]
