# Generated by Django 5.1.4 on 2024-12-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('medecin', 'Medecin'), ('infirmier', 'Infirmier'), ('patient', 'Patient')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('nom_etablissement', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('numero_ordre', models.CharField(max_length=50, unique=True)),
                ('specialite', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Radiologue',
            fields=[
                ('id_utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('etablissement', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.utilisateur')),
                ('service', models.CharField(max_length=100)),
                ('hospital_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infirmiers', to='users.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('NSS', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('date_naissance', models.DateField()),
                ('adresse', models.CharField(max_length=200)),
                ('mutuelle', models.CharField(blank=True, max_length=100, null=True)),
                ('personne_contact_nom', models.CharField(max_length=100)),
                ('personne_contact_telephone', models.CharField(max_length=20)),
                ('hopital_residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.hospital')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.utilisateur')),
                ('medecin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='users.medecin')),
            ],
        ),
    ]
