# Generated by Django 5.1.4 on 2024-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilisateur_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='activation_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='reset_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
