# Generated by Django 5.1.4 on 2025-01-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                ("id_medicament", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantite", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                ("id_ordonnance", models.AutoField(primary_key=True, serialize=False)),
                ("date_prescription", models.DateField(auto_now=True)),
                ("served_ordonnance", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic", models.TextField(blank=True, null=True)),
                ("symptomes", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BilanRadiologique",
            fields=[
                (
                    "id_bilanradiologique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField(auto_now=True)),
                ("description", models.TextField(blank=True, default="")),
                ("compte_rendu", models.TextField(blank=True)),
                ("type", models.TextField(default="")),
                (
                    "radiologue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilanradiologiques",
                        to="users.radiologue",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilans_radiologiques",
                        to="medical_record.consultation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BilanBiologique",
            fields=[
                (
                    "id_bilanbiologique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.TextField(default="")),
                ("date", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("done", "Done"),
                            ("validated", "Validated"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "laborantin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilanbiologiques",
                        to="users.laborantin",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilans_biologiques",
                        to="medical_record.consultation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DPI",
            fields=[
                ("id_dpi", models.AutoField(primary_key=True, serialize=False)),
                ("antecedents", models.TextField(blank=True)),
                ("qr_code", models.ImageField(unique=True, upload_to="qrcodes/")),
                (
                    "medecin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medcin",
                        to="users.medecin",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="medical_record.dpi",
            ),
        ),
        migrations.CreateModel(
            name="Mesure",
            fields=[
                ("id_mesure", models.AutoField(primary_key=True, serialize=False)),
                ("param", models.CharField(max_length=100)),
                ("valeur", models.CharField(max_length=100)),
                (
                    "bilan_biologique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesures",
                        to="medical_record.bilanbiologique",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="ordonnance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="medical_record.ordonnance",
            ),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id_prescription",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dose", models.CharField(max_length=20)),
                ("duree", models.PositiveIntegerField()),
                (
                    "medicament",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="medical_record.medicament",
                    ),
                ),
                (
                    "ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical_record.ordonnance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadioImage",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="radios/")),
                (
                    "bilan_radiologique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="medical_record.bilanradiologique",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consultation",
            name="resume",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="medical_record.resume",
            ),
        ),
        migrations.CreateModel(
            name="Soin",
            fields=[
                ("id_soin", models.AutoField(primary_key=True, serialize=False)),
                ("date_soin", models.DateField(auto_now=True)),
                ("description_medecin", models.CharField(max_length=200)),
                ("observation", models.TextField()),
                (
                    "dpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soins",
                        to="medical_record.dpi",
                    ),
                ),
                (
                    "infirmier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soins",
                        to="users.infirmier",
                    ),
                ),
            ],
        ),
    ]
