# Generated by Django 5.1.4 on 2025-01-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BilanBiologique",
            fields=[
                (
                    "id_bilanbiologique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.TextField(default="")),
                ("date", models.DateField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("done", "Done"),
                            ("validated", "Validated"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BilanRadiologique",
            fields=[
                (
                    "id_bilanradiologique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField(auto_now=True)),
                ("description", models.TextField(blank=True, default="")),
                ("compte_rendu", models.TextField(blank=True)),
                ("type", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DPI",
            fields=[
                ("id_dpi", models.AutoField(primary_key=True, serialize=False)),
                ("antecedents", models.TextField(blank=True)),
                ("qr_code", models.ImageField(unique=True, upload_to="qrcodes/")),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                ("id_medicament", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("quantite", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Mesure",
            fields=[
                ("id_mesure", models.AutoField(primary_key=True, serialize=False)),
                ("param", models.CharField(max_length=100)),
                ("valeur", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                ("id_ordonnance", models.AutoField(primary_key=True, serialize=False)),
                ("date_prescription", models.DateField(auto_now=True)),
                ("served_ordonnance", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id_prescription",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dose", models.CharField(max_length=20)),
                ("duree", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RadioImage",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="radios/")),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic", models.TextField(blank=True, null=True)),
                ("symptomes", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Soin",
            fields=[
                ("id_soin", models.AutoField(primary_key=True, serialize=False)),
                ("date_soin", models.DateField(auto_now=True)),
                ("description_medecin", models.CharField(max_length=200)),
                ("observation", models.TextField()),
            ],
        ),
    ]
