# Generated by Django 5.1.4 on 2024-12-31 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                ("id_medicament", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                ("id_ordonnance", models.AutoField(primary_key=True, serialize=False)),
                ("date_prescription", models.DateField()),
                ("etat_ordonnance", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic", models.TextField(blank=True, null=True)),
                ("symptomes", models.TextField(blank=True, null=True)),
                ("antecedents", models.TextField(blank=True, null=True)),
                ("autres_informations", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BilanBiologique",
            fields=[
                (
                    "id_bilanbiologique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.TextField(default="")),
                (
                    "laborantin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilanbiologiques",
                        to="users.laborantin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BilanRadiologique",
            fields=[
                (
                    "id_bilanradiologique",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("description", models.TextField(default="")),
                ("type", models.TextField(default="")),
                ("compte_rendu", models.TextField()),
                (
                    "radiologue",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bilanradiologiques",
                        to="users.radiologue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DPI",
            fields=[
                ("id_dpi", models.AutoField(primary_key=True, serialize=False)),
                ("antecedents", models.TextField(blank=True)),
                ("qr_code", models.ImageField(unique=True, upload_to="qrcodes/")),
                (
                    "medecin",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medcin",
                        to="users.medecin",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParametreBioMesure",
            fields=[
                (
                    "id_parametrebiomesure",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nom", models.CharField(max_length=100)),
                ("unite_mesure", models.CharField(max_length=20)),
                ("valeur_normale", models.CharField(max_length=100)),
                ("valeur_mesuree", models.CharField(max_length=100)),
                ("date_mesure", models.DateField()),
                (
                    "bilan_biologique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametre_bio_mesures",
                        to="medical_record.bilanbiologique",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bilanbiologique",
            name="parametres_bio_mesures",
            field=models.ManyToManyField(
                related_name="bilans_biologiques",
                to="medical_record.parametrebiomesure",
            ),
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id_prescription",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dose", models.CharField(max_length=50)),
                ("duree", models.CharField(max_length=50)),
                (
                    "medicament",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescription",
                        to="medical_record.medicament",
                    ),
                ),
                (
                    "ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="medical_record.ordonnance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadiologyImage",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="radiologies/")),
                (
                    "bilan_radiologique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="medical_record.bilanradiologique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id_consultation",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date_consult", models.DateField(auto_now=True)),
                (
                    "bilan_biologique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="medical_record.bilanbiologique",
                    ),
                ),
                (
                    "bilan_radiologue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="medical_record.bilanradiologique",
                    ),
                ),
                (
                    "dpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="medical_record.dpi",
                    ),
                ),
                (
                    "ordonnance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation",
                        to="medical_record.ordonnance",
                    ),
                ),
                (
                    "resume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation",
                        to="medical_record.resume",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soin",
            fields=[
                ("id_soin", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.CharField(max_length=255)),
                ("date_soin", models.DateField()),
                ("observation", models.TextField()),
                (
                    "dpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soins",
                        to="medical_record.dpi",
                    ),
                ),
                (
                    "infirmier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soins",
                        to="users.infirmier",
                    ),
                ),
            ],
        ),
    ]
