# Generated by Django 5.1.4 on 2025-01-04 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_record", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bilanbiologique",
            name="laborantin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bilanbiologiques",
                to="users.laborantin",
            ),
        ),
        migrations.AddField(
            model_name="bilanradiologique",
            name="radiologue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bilanradiologiques",
                to="users.radiologue",
            ),
        ),
        migrations.AddField(
            model_name="bilanradiologique",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bilans_radiologiques",
                to="medical_record.consultation",
            ),
        ),
        migrations.AddField(
            model_name="bilanbiologique",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bilans_biologiques",
                to="medical_record.consultation",
            ),
        ),
        migrations.AddField(
            model_name="dpi",
            name="medecin",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medcin",
                to="users.medecin",
            ),
        ),
        migrations.AddField(
            model_name="dpi",
            name="patient",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.patient",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="medical_record.dpi",
            ),
        ),
        migrations.AddField(
            model_name="mesure",
            name="bilan_biologique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mesures",
                to="medical_record.bilanbiologique",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="ordonnance",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="medical_record.ordonnance",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="medicament",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="medical_record.medicament",
            ),
        ),
        migrations.AddField(
            model_name="prescription",
            name="ordonnance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="medical_record.ordonnance",
            ),
        ),
        migrations.AddField(
            model_name="radioimage",
            name="bilan_radiologique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="medical_record.bilanradiologique",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="resume",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="medical_record.resume",
            ),
        ),
        migrations.AddField(
            model_name="soin",
            name="dpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soins",
                to="medical_record.dpi",
            ),
        ),
        migrations.AddField(
            model_name="soin",
            name="infirmier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soins",
                to="users.infirmier",
            ),
        ),
    ]
