# Generated by Django 5.1.4 on 2025-01-04 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_record", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="ordonnance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="medical_record.ordonnance",
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="resume",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="medical_record.resume",
            ),
        ),
    ]
