# Generated by Django 5.1.4 on 2025-01-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_record", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bilanbiologique",
            name="parametres_bio_mesures",
        ),
        migrations.RemoveField(
            model_name="radiologyimage",
            name="bilan_radiologique",
        ),
        migrations.RenameField(
            model_name="consultation",
            old_name="date_consult",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="ordonnance",
            old_name="etat_ordonnance",
            new_name="served_ordonnance",
        ),
        migrations.RenameField(
            model_name="resume",
            old_name="antecedents",
            new_name="details",
        ),
        migrations.RemoveField(
            model_name="medicament",
            name="prix",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="autres_informations",
        ),
        migrations.RemoveField(
            model_name="soin",
            name="description",
        ),
        migrations.AddField(
            model_name="bilanbiologique",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bilanradiologique",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="soin",
            name="description_medecin",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bilanradiologique",
            name="compte_rendu",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bilanradiologique",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="ordonnance",
            name="date_prescription",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="dose",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="duree",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="prescription",
            name="medicament",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescription",
                to="medical_record.medicament",
            ),
        ),
        migrations.AlterField(
            model_name="soin",
            name="date_soin",
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ParametreMesure",
            fields=[
                ("id_mesure", models.AutoField(primary_key=True, serialize=False)),
                ("param", models.CharField(max_length=100)),
                ("valeur", models.CharField(max_length=100)),
                (
                    "bilan_biologique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametre_bio_mesures",
                        to="medical_record.bilanbiologique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadioImage",
            fields=[
                ("id_image", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="radios/")),
                (
                    "bilan_radiologique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="medical_record.bilanradiologique",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ParametreBioMesure",
        ),
        migrations.DeleteModel(
            name="RadiologyImage",
        ),
    ]
