# Generated by Django 5.1.4 on 2024-12-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CertificatMedical',
            fields=[
                ('id_certificat', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Compte_Rendu',
            fields=[
                ('id_compte_rendu', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField()),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id_diagnostic', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField()),
                ('validated', models.CharField(max_length=20)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('antecedents', models.JSONField()),
                ('consultation_date', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id_soin', models.AutoField(primary_key=True, serialize=False)),
                ('date_soin', models.DateTimeField()),
                ('description_soin', models.TextField()),
                ('observation_patient', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('infirmier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.infirmier')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DPI',
            fields=[
                ('id_dpi', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire_administratif', models.TextField()),
                ('chemin_QR_code', models.CharField(max_length=255)),
                ('certificatMedical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.certificatmedical')),
                ('compte_Rendu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.compte_rendu')),
                ('diagnostic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.diagnostic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('hospitalisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.hospital')),
                ('soin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medical_record.soin')),
            ],
        ),
    ]
