# Generated by Django 5.1.4 on 2025-01-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medecin",
            name="numero_ordre",
        ),
        migrations.AddField(
            model_name="medecin",
            name="hospital_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medecins",
                to="users.hospital",
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("medecin", "Medecin"),
                    ("patient", "Patient"),
                    ("infirmier", "Infirmier"),
                    ("pharmacien", "Pharmacien"),
                    ("laborantin", "Laborantin"),
                    ("radiologue", "Radiologue"),
                ],
                max_length=20,
            ),
        ),
    ]
